In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,11,size=(5,5))
arr

array([[ 7,  4,  1,  4,  5],
       [ 9,  3,  2,  1,  1],
       [ 8,  4,  3, 10,  5],
       [ 8,  5,  1,  7,  4],
       [ 5,  7,  4,  8,  7]])

# 1.Filtering

**1.1) Filter elements greater than 5**

In [4]:
arr[arr>5]

array([ 7,  9,  8, 10,  8,  7,  7,  8,  7])

**1.2) Filter the elements that are even**

In [8]:
arr[arr%2==0]

array([ 4,  4,  2,  8,  4, 10,  8,  4,  4,  8])

In [9]:
arr>5

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False, False,  True, False],
       [False,  True, False,  True,  True]])

In [11]:
(arr>5) & (arr%2==0)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False, False, False, False],
       [False, False, False,  True, False]])

**1.4) Filter the elements that are divisible by either 3 or 7**

In [14]:
arr[(arr%3==0) | (arr%7==0)]

array([7, 9, 3, 3, 7, 7, 7])

**1.5) Filter elements that based on condition on another array**

In [15]:
arr1=np.array([True,False,True,False,True])
arr[arr1]

array([[ 7,  4,  1,  4,  5],
       [ 8,  4,  3, 10,  5],
       [ 5,  7,  4,  8,  7]])

In [16]:
arr

array([[ 7,  4,  1,  4,  5],
       [ 9,  3,  2,  1,  1],
       [ 8,  4,  3, 10,  5],
       [ 8,  5,  1,  7,  4],
       [ 5,  7,  4,  8,  7]])

**1.6 Filter the elements that based on the another array**

In [17]:
arr

array([[ 7,  4,  1,  4,  5],
       [ 9,  3,  2,  1,  1],
       [ 8,  4,  3, 10,  5],
       [ 8,  5,  1,  7,  4],
       [ 5,  7,  4,  8,  7]])

In [18]:
arr[2]

array([ 8,  4,  3, 10,  5])

In [19]:
arr[2,1:]

array([ 4,  3, 10,  5])

In [20]:
arr[2,:]>5

array([ True, False, False,  True, False])

In [25]:
arr[arr[2,:]>5]

array([[7, 4, 1, 4, 5],
       [8, 5, 1, 7, 4]])

# 2.Aggregate Functions

**2.1 Sum**

In [26]:
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print('-'*20)

arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

15
--------------------
21
[5 7 9]
[ 6 15]


**2.2.)mean**

In [30]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

3.5
[2.5 3.5 4.5]
[2. 5.]


**2.3 Standard deviation**

In [31]:
arr=np.array([1,2,3,4,5])
print(np.std(arr))

arr=np.array([[1,2,3],[4,5,6]])
print(np.std(arr))

1.4142135623730951
1.707825127659933


**2.4 min-max**

In [32]:
arr=np.array([1,2,3,4,5])
print(np.min(arr))

arr=np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

print('-'*20)

arr=np.array([1,2,3,4,5])
print(np.max(arr))

arr=np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))

1
1
[2.5 3.5 4.5]
[2. 5.]
--------------------
5
6
[4 5 6]
[3 6]
