In [1]:
import numpy as np

# 1. Searching

In [5]:
arr=np.array([1,3,4,6,3,5,7,4,3,5,12,13])

#linear search

index=np.where(arr==3)[0]
print(index)

#binary search

index=np.searchsorted(arr,3)
print(index)

#searching for closest value

index=np.argmin(abs(arr-11))
print(index)

[1 4 8]
1
10


# 2. Sorting

In [10]:
arr=np.array([5,7,9,0,3,1,6,2,4,8])

#by default its using Quick Sort

sorted_arr=np.sort(arr)
print(sorted_arr)

#quicksort

sorted_arr=np.sort(arr,kind='quicksort')
print(sorted_arr)

#heapsort

sorted_arr=np.sort(arr,kind='heapsort')
print(sorted_arr)

#quicksort

sorted_arr=np.sort(arr,kind='mergesort')
print(sorted_arr)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
