# A Deep dive into range,arange,linspace

In [1]:
import numpy as np

**1. Range**

In [15]:
for i in range(10):
    print(i)

#The following function is not possible 
#in list but is possible in numpy array

# r=range(0,10,.5)
# print(r)

0
1
2
3
4
5
6
7
8
9


In [4]:
r=range(10,0,-2)
print(r)
print(5 in r)
print(10 in r)

range(10, 0, -2)
False
True


In [5]:
for i in range(10,0,-2):
    print(i)

10
8
6
4
2


In [6]:
r=range(1,6)
print(list(r))

[1, 2, 3, 4, 5]


**2. arange**

In [13]:
arr=np.arange(0,10,2)
print(arr)

arr=np.arange(10,0,-1)
print(arr)

arr=np.arange(0,10,0.5)
print(arr)

[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


**3. Linspace**

In [22]:
l=np.linspace(0,10,5)
print(l)

l=np.linspace(1,10,9)
print(l)

l=np.linspace(1,10,10,endpoint=False)
print(l)

l,s=np.linspace(1,5,10,retstep=True)
print(l)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
0.4444444444444444


In [18]:
l=np.arange(0,11,5)
print(l)

[ 0  5 10]


**4. logspace**

In [24]:
arr=np.logspace(0,10,5)
print(arr)

arr=np.logspace(0,10,5,endpoint=False)
print(arr)

arr=np.logspace(0,10,5,base=2)
print(arr)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


# Array manipulation essentials: Reshaing ,Flattening ,Splitting

**1. Flattening**

In [27]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

flat_arr=arr.flatten()
print(flat_arr)

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

flat_arr=arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[1 2 3 4 5 6 1 2 3 4 5 6]


**2. Reshaping**

In [36]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

reshaped_arr=np.reshape(arr,(6,1))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**3. Splitting**

vsplit

In [43]:
arr=np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[10,11,12,13]])
print(arr)

print(np.vsplit(arr,2))
for i in np.vsplit(arr,4):
    print(i)

[[ 1  2  3  2]
 [ 4  5  6  2]
 [ 7  8  9  2]
 [10 11 12 13]]
[array([[1, 2, 3, 2],
       [4, 5, 6, 2]]), array([[ 7,  8,  9,  2],
       [10, 11, 12, 13]])]
[[1 2 3 2]]
[[4 5 6 2]]
[[7 8 9 2]]
[[10 11 12 13]]


-hsplit

In [44]:
arr=np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[10,11,12,13]])
print(arr)

print(np.hsplit(arr,2))
for i in np.hsplit(arr,4):
    print(i)

[[ 1  2  3  2]
 [ 4  5  6  2]
 [ 7  8  9  2]
 [10 11 12 13]]
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3,  2],
       [ 6,  2],
       [ 9,  2],
       [12, 13]])]
[[ 1]
 [ 4]
 [ 7]
 [10]]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 3]
 [ 6]
 [ 9]
 [12]]
[[ 2]
 [ 2]
 [ 2]
 [13]]


**Split**

In [52]:
arr=np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[10,11,12,13]])
print(arr)

print('-'*20)

split_arr=np.split(arr,2,axis=1)
print(split_arr)

#axis=0 denotes vsplit
#axis=1 denotes hsplit
#by default the split is vertical split vsplit

[[ 1  2  3  2]
 [ 4  5  6  2]
 [ 7  8  9  2]
 [10 11 12 13]]
--------------------
[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3,  2],
       [ 6,  2],
       [ 9,  2],
       [12, 13]])]


**4. Merging**

#concatenate

In [55]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,5,6,4])
arr3=np.array([8,7,3,4])
arr4=np.array([9,2,10,4])

concat_arr=np.concatenate((arr1,arr2))
concat_arr2=np.concatenate((arr1,arr2,arr3))
concat_arr3=np.concatenate((arr1,arr2,arr3,arr4))
print(concat_arr)
print(concat_arr2)
print(concat_arr3)

[1 2 3 4 1 5 6 4]
[1 2 3 4 1 5 6 4 8 7 3 4]
[ 1  2  3  4  1  5  6  4  8  7  3  4  9  2 10  4]


#hstack

In [56]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,5,6,4])
arr3=np.array([8,7,3,4])
arr4=np.array([9,2,10,4])

concat_arr=np.hstack((arr1,arr2,arr3,arr4))
print(concat_arr)

[ 1  2  3  4  1  5  6  4  8  7  3  4  9  2 10  4]


#vstack

In [57]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,5,6,4])
arr3=np.array([8,7,3,4])
arr4=np.array([9,2,10,4])

concat_arr=np.vstack((arr1,arr2,arr3,arr4))
print(concat_arr)

[[ 1  2  3  4]
 [ 1  5  6  4]
 [ 8  7  3  4]
 [ 9  2 10  4]]


#stack

In [60]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,5,6,4])
arr3=np.array([8,7,3,4])
arr4=np.array([9,2,10,4])

concat_arr=np.stack((arr1,arr2,arr3,arr4),axis=0)
print(concat_arr)

concat_arr=np.stack((arr1,arr2,arr3,arr4),axis=1)
print(concat_arr)

[[ 1  2  3  4]
 [ 1  5  6  4]
 [ 8  7  3  4]
 [ 9  2 10  4]]
[[ 1  1  8  9]
 [ 2  5  7  2]
 [ 3  6  3 10]
 [ 4  4  4  4]]


# Advanced Multidimensional Indexing

In [78]:
arr=np.array([[[1,2,3],[-3,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [-3,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr.shape

(2, 2, 3)

In [63]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [64]:
print(arr[0][1])

[4 5 6]


In [65]:
print(arr[0][1][2])

6


In [67]:
print(arr[0,1,2])

6


In [69]:
print(arr[0,1])

[4 5 6]


In [70]:
print(arr[0,:,:])

[[1 2 3]
 [4 5 6]]


In [71]:
print(arr[:,1,:])

[[ 4  5  6]
 [10 11 12]]


In [73]:
#accessing with specific conditions

print(arr[[0],[0,1],:])

[[1 2 3]
 [4 5 6]]


In [79]:
print(arr)
print('*'*20)
arr[arr>5]=0
print(arr)
arr[arr>=18]=True
print(arr)

[[[ 1  2  3]
  [-3  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
********************
[[[ 1  2  3]
  [-3  5  0]]

 [[ 0  0  0]
  [ 0  0  0]]]
[[[ 1  2  3]
  [-3  5  0]]

 [[ 0  0  0]
  [ 0  0  0]]]


# Broadcasting for efficient calculations

**1. Arithmetic**

In [87]:
a=np.array([1,2,3])
b=np.array([[10,20,20],[40,50,60]])

print(a)
print(b)

#addition 
print(a+b)
print(a+5)
print(a+10)

#subtraction

print(a-2)
print(a-b)

#multiplication

print(a*2)
print(a*b)

#division

print(a/2)
print(a/b)

#exponentiation

print(a**2)
print(a**b)

#modulo

print(a%2)
print(a%b)

[1 2 3]
[[10 20 20]
 [40 50 60]]
[[11 22 23]
 [41 52 63]]
[6 7 8]
[11 12 13]
[-1  0  1]
[[ -9 -18 -17]
 [-39 -48 -57]]
[2 4 6]
[[ 10  40  60]
 [ 40 100 180]]
[0.5 1.  1.5]
[[0.1   0.1   0.15 ]
 [0.025 0.04  0.05 ]]
[1 4 9]
[[          1     1048576  -808182895]
 [          1           0 -1830685263]]
[1 0 1]
[[1 2 3]
 [1 2 3]]


**2. Comparison**

In [96]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

print(a)
print(b)
print('*'*20)

# > (greater than)

print(a>b)
print(a>2)
print('*'*20)

# < (lesser than)

print(a<b)
print(a<2)
print('*'*20)


# >= (greater than equals to)

print(a>=b)
print(a>=2)
print('*'*20)

# <= (lesser than equals to)

print(a<=b)
print(a<=2)
print('*'*20)

# == (equals to)

print(a==b)
print(a==2)
print('*'*20)

# != (not equals to)

print(a!=b)
print(a!=2)
print('*'*20)

[1 2 3]
[[1 2 3]
 [4 5 6]]
********************
[[False False False]
 [False False False]]
[False False  True]
********************
[[False False False]
 [ True  True  True]]
[ True False False]
********************
[[ True  True  True]
 [False False False]]
[False  True  True]
********************
[[ True  True  True]
 [ True  True  True]]
[ True  True False]
********************
[[ True  True  True]
 [False False False]]
[False  True False]
********************
[[False False False]
 [ True  True  True]]
[ True False  True]
********************


**Logical**

In [99]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

print(a)
print('*'*20)
print(b)
print('*'*20)

print(a&b)
print('*'*20)

print(a|b)
print('*'*20)

print(a^b)
print('*'*20)

[1 2 3]
********************
[[1 2 3]
 [4 5 6]]
********************
[[1 2 3]
 [0 0 2]]
********************
[[1 2 3]
 [5 7 7]]
********************
[[0 0 0]
 [5 7 5]]
********************


**Bitwise operator**

In [103]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])

print(a)
print('*'*20)
print(b)
print('*'*20)

print(np.bitwise_and(a,b))
print('*'*20)

print(np.bitwise_or(a,b))
print('*'*20)

print(np.bitwise_xor(a,b))
print('*'*20)

print(np.bitwise_not(a,b))
print('*'*20)

print(np.right_shift(a,b))
print('*'*20)

print(np.left_shift(a,b))
print('*'*20)

[1 2 3]
********************
[[1 2 3]
 [4 5 6]]
********************
[[1 2 3]
 [0 0 2]]
********************
[[1 2 3]
 [5 7 7]]
********************
[[0 0 0]
 [5 7 5]]
********************
[[-2 -3 -4]
 [-2 -3 -4]]
********************
[[0 0 0]
 [0 0 0]]
********************
[[0 0 0]
 [0 0 0]]
********************


In [105]:
(np.arange(0,100,2)>50).tolist().count(False)

26

In [106]:
(np.arange(0,100,2)>50).tolist().count(True)

24

# Locating Elements with where

**1. Where clause with 1 d array**

In [113]:
np.random.seed(42)
arr=np.random.randint(1,11,size=10)
print(arr)
print('*'*20)
print(np.where(arr>=5))
print(arr[np.where(arr>=5)])

indices=np.where(arr>=5)
print(list(indices[0]))
print('*'*20)

print(arr[indices])

[ 7  4  8  5  7 10  3  7  8  5]
********************
(array([0, 2, 3, 4, 5, 7, 8, 9], dtype=int64),)
[ 7  8  5  7 10  7  8  5]
[0, 2, 3, 4, 5, 7, 8, 9]
********************
[ 7  8  5  7 10  7  8  5]


**2D array**

In [115]:
np.random.seed(42)
arr=np.random.randint(1,11,size=(3,3))

print(arr)
print('*'*20)
indices=np.where(arr>=5)
print(indices)
print('*'*20)

print(arr[indices])

[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]
********************
(array([0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 1, 2, 1, 2], dtype=int64))
********************
[ 7  8  5  7 10  7  8]


**3D Array**

In [116]:
np.random.seed(42)
arr=np.random.randint(1,11,size=(3,3,3))

print(arr)
print('*'*20)
indices=np.where(arr>=5)
print(indices)
print('*'*20)

print(arr[indices])

[[[ 7  4  8]
  [ 5  7 10]
  [ 3  7  8]]

 [[ 5  4  8]
  [ 8  3  6]
  [ 5  2  8]]

 [[ 6  2  5]
  [ 1 10  6]
  [ 9  1 10]]]
********************
(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
      dtype=int64), array([0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2],
      dtype=int64), array([0, 2, 0, 1, 2, 1, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2],
      dtype=int64))
********************
[ 7  8  5  7 10  7  8  5  8  8  6  5  8  6  5 10  6  9 10]
