# Array v/s List Comparison

In [12]:
import numpy as np

lst=[1,3,2]
print(lst)
print(type(lst))

[1, 3, 2]
<class 'list'>


In [13]:
arr=np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [14]:
print(arr==lst)

[ True False False]


In [15]:
print(arr.tolist()==lst)

False


In [16]:
print(sorted(arr.tolist())==sorted(lst))

True


# Adding elements in an array v/s list

In [20]:
lst=[1,3,2]
arr=np.array([1,2,3])

print(lst)
lst.append(4)
print(lst)

print(arr)
arr=np.append(arr,4)
print(arr)

[1, 3, 2]
[1, 3, 2, 4]
[1 2 3]
[1 2 3 4]


# Removing the elements in an Array v/s list

In [23]:
lst=[1,3,2]
arr=np.array([1,2,3])

print(lst)
#lst.pop()
del lst[-2]
print(lst)

print(arr)
arr=np.delete(arr,-2)
print(arr)

[1, 3, 2]
[1, 2]
[1 2 3]
[1 3]


# Updating elements in an array v/s list

In [26]:
lst=[1,3,2]
print(lst)
lst[-1]=4
print(lst)
print('*'*20)

arr=np.array([1,3,2])
print(arr)
arr[-2]=2
arr[-1]=3
print(arr)

[1, 3, 2]
[1, 3, 4]
********************
[1 3 2]
[1 2 3]


# List vs Array comparisons

In [39]:
import time

my_list=list(range(10000000))
my_array=np.arange(10000000)

#search time for list 
start_time=time.time()
for _ in range(100):
    if 5000000 in my_list:
        pass
end_time=time.time()
print("for the list ",end_time-start_time)

#search time for array
start_time=time.time()
for _ in range(100):
    if 5000000 in my_array:
        pass
end_time=time.time()
print("for the array",end_time-start_time)


print(len(my_list))
print(len(my_array))

for the list  4.734694480895996
for the array 0.5884983539581299
10000000
10000000


In [30]:
my_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
my_array[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Converting Data Structures to Numpy Array

**1.1 Converting a tuple to an array**

In [40]:
tpl=(1,2,3)
print(tpl)
print(type(tpl))

arr=np.array(tpl)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


**1.2 Converting a list to an array**

In [41]:
lst=[1,2,3]
print(lst)
print(type(lst))

arr=np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


**1.3 Converting a dictionary to an array**

In [45]:
dict={1:"apple",2:"mango",3:"grapes"}
print(dict)
print(type(dict))

arr=np.array(dict)
print(arr)
print(type(arr))

arr_k=np.array(list(dict.keys()))
arr_v=np.array(list(dict.values()))
print(arr_k)
print(type(arr_k))
print(arr_v)
print(type(arr_v))

{1: 'apple', 2: 'mango', 3: 'grapes'}
<class 'dict'>
{1: 'apple', 2: 'mango', 3: 'grapes'}
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
['apple' 'mango' 'grapes']
<class 'numpy.ndarray'>


**1.4 Converting a set to an array**

In [47]:
st={1,2,3}
print(st)
print(type(st))

arr=np.array(list(st))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
[1 2 3]
<class 'numpy.ndarray'>


**1.5 Converting a string to an array**

In [48]:
arr=np.array(list('hello world'))
print(arr)
print(type(arr))


['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


# Converting the datatype of numpy array

**2.1 Create an array of integers**

In [52]:
arr=np.array([1,2,3,4,5])
print(arr)
arr_=arr.astype('float')
print(arr_)
arr__=arr.astype('str')
print(arr__)
arr___=arr.astype('bool')
print(arr___)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


**2.2 Create an array of floats**

In [55]:
arr=np.array([1.,2.,3.,4.,5.])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr__=arr.astype('str')
print(arr__)
arr___=arr.astype('bool')
print(arr___)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


**2.3 Create an array of strings**

In [59]:
arr=np.array(['1','2','3','4','5'])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr__=arr.astype('float')
print(arr__)
arr___=arr.astype('bool')
print(arr___)

['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]


**2.4 Create an array of boolean**

In [60]:
arr=np.array([True,False,False,False,True])
print(arr)
arr_=arr.astype('int')
print(arr_)
arr__=arr.astype('float')
print(arr__)
arr___=arr.astype('str')
print(arr___)

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']


In [62]:
arr=np.array([True,False,False,False,True])
arr_=arr.astype('int')
arr_=arr_.astype('str')
print(arr_)

['1' '0' '0' '0' '1']


# Manipulating Multidimensional arrays

# 1. Creating Multi-dimensional Arrays

**1.1 Create a 2D array from a list of lists**

In [65]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print('*'*20)


[[1 2 3]
 [4 5 6]]
********************


**1.2 Create a 3D array from a list of lists**

In [67]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


**1.3 Creating a 2d array from a list of tuples**

In [69]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr)
print('*'*20)

[[1 2 3]
 [4 5 6]]
********************


**1.4 Creating a 2D array from a list of arrays**

In [71]:
arr=np.array([np.array([1,2,3]),np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


**Create a 2D array from a list of strings**

In [72]:
arr=np.array([['1','2','3'],['4','5','6']])
print(arr)
print('*'*20)

[['1' '2' '3']
 ['4' '5' '6']]
********************


**1.6 Create a 2D array from a list of dictionaries**

In [73]:
arr=np.array([{'a':1,'b':2,'c':3},{'d':4,'e':5,'f':6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


# 2. Finding details of an arrays

**2.1 Finding the shape of the array**

In [74]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


**2.2 Print the number of dimensions of the array**

In [75]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


**2.3 Print the data type of the array**

In [76]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.dtype)

int32


**2.4 Print the size of the array**

In [77]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


**2.5 Print the item size| bytes taken by each element in an array**

In [78]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.itemsize)

4


**2.6 Print the type of the array**

In [79]:
print(type(arr))

<class 'numpy.ndarray'>


# Working with a copy fnction

**1. Copy functions with lists**

In [86]:
lst=[1,2,3,4,5]
print(lst)
lst1=lst
print(lst1)
print('-'*20)
lst[0]=5
print(lst)
print(lst1)
print('*'*20)
lst=[1,2,3,4,5]
print(lst)
lst1=lst.copy()
print(lst1)
print('-'*20)
lst[0]=5
print(lst)
print(lst1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
--------------------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
********************
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
--------------------
[5, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


**Copy functions with arrays**

In [88]:
arr=np.array([1,2,3,4,5])
arr_=arr.copy()

print(arr)
print(arr_)
print('-'*10)

arr[0]=5
print(arr)
print(arr_)
arr[0]=1
print('-'*10)

arr_[0]=5
print(arr)
print(arr_)

[1 2 3 4 5]
[1 2 3 4 5]
----------
[5 2 3 4 5]
[1 2 3 4 5]
----------
[1 2 3 4 5]
[5 2 3 4 5]


# Exploring Indexing and Slicing in NumPy

**1.Indexing and slicing with lists**

In [102]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[4])

1
5


In [103]:
print(arr[-1])

9


In [104]:
print(arr[0:3])

[1 2 3]


In [105]:
print(arr[0:100])

[1 2 3 4 5 6 7 8 9]


In [106]:
print(arr[0:])

[1 2 3 4 5 6 7 8 9]


In [107]:
print(arr[1:-1])

[2 3 4 5 6 7 8]


In [108]:
print(arr[::2])

[1 3 5 7 9]


In [109]:
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


In [116]:
# del arr[0]
arr=np.delete(arr,0)
arr

array([100, 200,   4,   5,   6,   7,   8,   9])

In [117]:
print(arr)

[100 200   4   5   6   7   8   9]


In [118]:
arr[1:3]=[100,200]
print(arr)

[100 100 200   5   6   7   8   9]


In [119]:
arr=np.insert(arr,0,5)
arr

array([  5, 100, 100, 200,   5,   6,   7,   8,   9])

# Creating fixed size arrays

**1. Creating zeros**

In [121]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [123]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [126]:
np.zeros((2,3,5),dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [127]:
np.zeros((2,3,5),dtype=str)

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

**2.Ones**

In [130]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**3. Eye**

In [131]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [135]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**4. Generating the random numbers**

In [136]:
np.random.rand()

0.8024531886818398

In [137]:
print(np.random.rand(10))

[0.72736811 0.30803408 0.40527385 0.31308816 0.84377237 0.32266657
 0.19357951 0.82733019 0.39440088 0.42221078]


In [138]:
print(np.random.rand(3,3))

[[0.11304863 0.32925042 0.86393367]
 [0.09797925 0.29710202 0.69873915]
 [0.07262424 0.56716224 0.35288138]]


In [139]:
np.random.randint(10)

9

In [140]:
np.random.randint(10,size=(3,3))

array([[6, 1, 1],
       [5, 5, 3],
       [3, 6, 3]])

In [143]:
np.random.randint(low=1,high=7,size=(6,6))

array([[2, 6, 1, 4, 5, 4],
       [5, 1, 3, 4, 3, 1],
       [4, 1, 3, 6, 5, 4],
       [5, 1, 4, 4, 3, 2],
       [2, 1, 5, 2, 6, 2],
       [2, 4, 1, 6, 4, 6]])

In [144]:
np.random.randn()

-0.6768483633114443

**Uniform distribution**

In [148]:
arr=(np.random.randint(low=1,high=7,size=(100)))

In [149]:
for i in range(1,7):
    print(i,arr.tolist().count(i))

1 15
2 17
3 15
4 13
5 14
6 26


**Concept of random seed**

In [150]:
np.random.seed(42)

In [151]:
for i in range(10):
    arr=np.random.randint(2,size=1000)
    print(len(arr[arr==1]),len(arr[arr==0]))

510 490
474 526
499 501
524 476
489 511
486 514
491 509
506 494
503 497
505 495
