In [1]:
import numpy as np

# 1. textFile

In [3]:

data = np.loadtxt("data.txt", delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


# 2. npy file

In [5]:
data = np.load("data.npy")
print(data)

[[1 2 3]
 [4 5 6]]


# 3. csv

In [7]:
data= np.loadtxt('data.csv',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


# 4. json

In [8]:
data= np.loadtxt('data.json',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


# 5. yml

In [9]:
data= np.loadtxt('data.yaml',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
