In [1]:
import numpy as np
data=np.array([1,2,3])
np.savetxt('data.txt',data,delimiter=',')
print(data)

[1 2 3]


In [2]:

data = np.load('data2.npy')
print(data)

[[1 2 3]
 [4 5 6]]


In [3]:
np.savetxt('data.txt', data, delimiter = ',')
print(data)

[[1 2 3]
 [4 5 6]]
