In [1]:
import numpy as np

# 1. Replacing existing content

In [3]:
data=np.array([1,2,3])
np.savetxt('data-1.txt',data,delimiter=',')

data=np.array([4,5,6])
np.savetxt('data-2.txt',data,delimiter=',')


# 2. Appending the data on existing file

In [4]:
data=np.load('data.npy')
np.savetxt('data.txt',data,delimiter=',')

In [1]:
import numpy as np

In [10]:
data=np.array([1,2,3])
np.savetxt('data.txt',data,delimiter=',')
print(data)

[1 2 3]


In [11]:
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


In [9]:
data = np.load('data.npy')
print(data)
np.savetxt('data.txt', data, delimiter = ',')
print(data)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
